"""Registry of the 98 CUA-Gym-Hub mock websites.

Each mock exposes an identical HTTP state API (``/post``, ``/go``, ``/state``,
``/upload``) as documented in ``hub/README.md`` and
``.claude/skills/mock_websites/SKILL.md``. This module maps a mock's
directory name (e.g. ``"12306_mock"``) to its deployment port (for local /
self-hosted deployments via ``hub/deploy-all.sh``) and its public URL slug
(for the hosted ``https://cua-gym-<slug>.xlang.ai`` deployments).

The port table below mirrors ``docs/mock_web_docs/README.md`` (generated by
``ops/generate_mock_web_docs.py``). The slug follows the rule confirmed for
the publicly documented mocks in ``.claude/skills/mock_websites/SKILL.md``:
``slug = name.removesuffix("_mock").lower().replace("_", "-")``. This is a
consistent heuristic for the remaining mocks; override it via
``PORTS``/``SLUG_OVERRIDES`` below or the ``host``/``base_url`` parameters on
:class:`WebEnv` if a given deployment differs.
"""

from __future__ import annotations

from typing import Optional

# name (directory under hub/websites/) -> local deployment port
PORTS: dict[str, int] = {
    "12306_mock": 8000,
    "Canvas-LMS_mock": 8001,
    "Expensify_mock": 8002,
    "PACS-viewer_mock": 8003,
    "SAP_mock": 8004,
    "ServiceNow_mock": 8005,
    "TradingView_mock": 8006,
    "Zendesk_mock": 8007,
    "adp_mock": 8008,
    "airtable_mock": 8009,
    "aliyun_mock": 8010,
    "amazon_mock": 8011,
    "amazon_seller_mock": 8012,
    "amplitude_mock": 8013,
    "asana_mock": 8014,
    "aws_console_mock": 8015,
    "azure_mock": 8016,
    "bamboohr_mock": 8017,
    "booking_com_mock": 8018,
    "canva_mock": 8019,
    "canvas_mock": 8020,
    "circleci_mock": 8021,
    "clio_mock": 8022,
    "cloudflare_mock": 8023,
    "coinbase_mock": 8024,
    "confluence_mock": 8025,
    "contractbook_mock": 8026,
    "datadog_mock": 8027,
    "dingtalk_mock": 8028,
    "discord_mock": 8029,
    "docusign_mock": 8030,
    "ebay_mock": 8031,
    "epic-health_mock": 8032,
    "expedia_mock": 8033,
    "facebook_mock": 8034,
    "feishu_mock": 8035,
    "github_mock": 8036,
    "gitlab_mock": 8037,
    "gmail_mock": 8038,
    "google_ads_mock": 8039,
    "google_analytics_mock": 8040,
    "google_calendar_mock": 8041,
    "google_docs_mock": 8042,
    "google_drive_mock": 8043,
    "google_flights_mock": 8044,
    "google_sheets_mock": 8045,
    "greenhouse_mock": 8046,
    "gusto_mock": 8047,
    "hotjar_mock": 8048,
    "hubspot_marketing_mock": 8049,
    "hubspot_mock": 8050,
    "instacart_mock": 8051,
    "instagram_mock": 8052,
    "jira_mock": 8053,
    "klaviyo_mock": 8054,
    "lattice_mock": 8055,
    "linear_mock": 8056,
    "linkedin_mock": 8057,
    "looker_studio_mock": 8058,
    "lucidchart_mock": 8059,
    "mailchimp_mock": 8060,
    "meta_ads_mock": 8061,
    "microsoft_teams_mock": 8062,
    "miro_mock": 8063,
    "mixpanel_mock": 8064,
    "monday_mock": 8065,
    "notion_mock": 8066,
    "openreview_mock": 8067,
    "outlook_web_mock": 8068,
    "paypal_mock": 8069,
    "pinterest_mock": 8070,
    "postman_mock": 8071,
    "quickbooks_mock": 8072,
    "reddit_mock": 8073,
    "robinhood_mock": 8074,
    "salesforce_mock": 8075,
    "sentry_mock": 8076,
    "shopify_admin_mock": 8077,
    "slack_mock": 8078,
    "stripe_dashboard_mock": 8079,
    "tableau_mock": 8080,
    "taobao_seller_mock": 8081,
    "trello_mock": 8082,
    "tripadvisor_mock": 8083,
    "twitter_mock": 8084,
    "uber_eats_mock": 8085,
    "vercel_mock": 8086,
    "wandb_mock": 8087,
    "wechat_mock": 8088,
    "weibo_mock": 8089,
    "westlaw_mock": 8090,
    "woocommerce_mock": 8091,
    "workday_mock": 8092,
    "xiaohongshu_mock": 8093,
    "youtube_mock": 8094,
    "zhihu_mock": 8095,
    "zillow_mock": 8096,
    "zoom_web_mock": 8097,
}

# Explicit slug overrides for names whose public-URL slug isn't a trivial
# lowercase(name without "_mock").replace("_","-") transform.
SLUG_OVERRIDES: dict[str, str] = {
    "Canvas-LMS_mock": "canvas-lms",
    "PACS-viewer_mock": "pacs-viewer",
    "SAP_mock": "sap",
    "ServiceNow_mock": "servicenow",
    "TradingView_mock": "tradingview",
    "Zendesk_mock": "zendesk",
    "Expensify_mock": "expensify",
}

DEFAULT_LOCAL_HOST = "163.7.16.44"
PUBLIC_URL_TEMPLATE = "https://cua-gym-{slug}.xlang.ai"


def slug_for(name: str) -> str:
    """Return the public-URL slug for a mock directory name.

    e.g. ``"aws_console_mock" -> "aws-console"``, ``"12306_mock" -> "12306"``.
    """
    if name in SLUG_OVERRIDES:
        return SLUG_OVERRIDES[name]
    base = name[:-5] if name.endswith("_mock") else name
    return base.lower().replace("_", "-")


def port_for(name: str) -> int:
    if name not in PORTS:
        raise KeyError(
            f"Unknown mock '{name}'. Known mocks: {sorted(PORTS)[:5]}... "
            f"({len(PORTS)} total)."
        )
    return PORTS[name]


def base_url(
    name: str,
    mode: str = "public",
    host: Optional[str] = None,
    port: Optional[int] = None,
    scheme: str = "http",
) -> str:
    """Resolve the base URL (no trailing slash, no ``?sid=``) for a mock.

    Args:
        name: mock directory name, e.g. ``"slack_mock"``.
        mode: ``"public"`` for the hosted ``cua-gym-*.xlang.ai`` deployment,
            ``"local"`` for a self-hosted deployment reachable by IP/hostname
            and port (see ``hub/DEPLOY.md``).
        host: overrides the default local host (only used when
            ``mode="local"``). Defaults to :data:`DEFAULT_LOCAL_HOST`.
        port: overrides the registry port (only used when ``mode="local"``).
        scheme: URL scheme for local mode (``"http"`` or ``"https"``).
    """
    if mode == "public":
        return PUBLIC_URL_TEMPLATE.format(slug=slug_for(name))
    if mode == "local":
        resolved_host = host or DEFAULT_LOCAL_HOST
        resolved_port = port if port is not None else port_for(name)
        return f"{scheme}://{resolved_host}:{resolved_port}"
    raise ValueError(f"Unknown url_mode: {mode!r} (expected 'public' or 'local')")


def all_mocks() -> list[str]:
    return sorted(PORTS)


REGISTRY = {name: {"port": PORTS[name], "slug": slug_for(name)} for name in PORTS}
